//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsAutoSleeper.cpp
//  @ Date : 2/8/2009
//  @ Author : 
//
//


#include "WsAutoSleeper.h"
#include "WsDashboard.h"

/**
 * Construcst a WsAutoSleeper
 */
WsAutoSleeper::WsAutoSleeper()
{
    ap_dashboard = WsDashboard::getInstance();

}

/**
 * Destroys a WsAutoSleeper
 */
WsAutoSleeper::~WsAutoSleeper()
{

}

/**
 * Used to initialize parameters.
 */
void WsAutoSleeper::initParams(void)
{
}

/**
 * Called by the autonomous manager every loop.  Everything on the robot
 * should be turned off here.
 */
bool WsAutoSleeper::run(void )
{
    //static float counter = 0;

    printf("SLEEP\n");

    turnOffDriveBase();
    turnOffAppendages();

    /*
    ap_dashboard->setValue(IDX_AUTO_DATA1, counter++);
    */

    return true;
}

