//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsCamera.cpp
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#include "WsCamera.h"
#include "Timer.h"
using namespace std;

WsCamera::WsCamera(AxisCamera *a)
{
  ap_camera = a;
  if(ap_camera != NULL)
  {
      ap_camera->WriteResolution(AxisCameraParams::kResolution_320x240);
      //ap_camera->WriteResolution(AxisCameraParams::kResolution_160x120);
      //ap_camera->WriteResolution(AxisCameraParams::kResolution_640x480);
      ap_camera->WriteBrightness(0);
      ap_camera->WriteExposureControl(AxisCameraParams::kExposure_Automatic);
      ap_camera->WriteExposurePriority(50);
      ap_camera->WriteCompression(20);
      Wait(3.0);
  }
  else
  {
    printf("!!! NULL CAMERA !!!\n");
  }
}

WsCamera::~WsCamera()
{

}

