//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsCamera.h
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#if !defined(_WSCAMERA_H)
#define _WSCAMERA_H

#include "Vision/ColorImage.h"
#include "Vision/AxisCamera.h"

class WsCamera
{
public:
    WsCamera(AxisCamera *a);
    ~WsCamera();
protected:
    AxisCamera *ap_camera;
};

#endif  //_WSCAMERA_H
