//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsCalibration.cpp
//  @ Date : 1/19/2009
//  @ Author : 
//
//


#include <stdarg.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "WsCalibration.h"

WsCalibration* WsCalibration::ap_instance = NULL;

/**
* Constructs a WsCalibration
*/
WsCalibration::WsCalibration()
{
  memset(a_data, 0, sizeof(a_data));
  a_competitionRobot = true;
  a_oldRobot = false;

  readData();
}

/**
* Destructs a WsCalibration
*/
WsCalibration::~WsCalibration()
{
    ap_instance = NULL;
}

/**
* Gets the WsCalibration singleton instance
* @returns The WsCalibration singleton instance
*/
WsCalibration* WsCalibration::getInstance()
{
  if (ap_instance == NULL)
  {
    ap_instance = new WsCalibration();
  }

  return ap_instance;
}

/**
* Deletes the WsCalibration singleton instance
*/
void WsCalibration::deleteInstance()
{
  if (ap_instance != NULL)
  {
    delete ap_instance;
  }
  ap_instance = NULL;
}

/**
* Saves the internal calibration data to the calibration file on the robot
*/
void WsCalibration::saveData()
{
  FILE *fptr = NULL;
  char buffer[100];
  int idx;

  fptr = fopen(CALIBRATION_FILENAME, "w");

  if (fptr != NULL)
  {
    for (idx = 0; idx < MAX_NUM_VALUES; idx++)
    {
      sprintf(buffer, "%d\n", a_data[idx]);
      fputs(buffer, fptr);
    }

    fflush(fptr);
    fclose(fptr);
  }
}

/**
* Reads the calibration file on the robot into the internal calibration data
*/
void WsCalibration::readData()
{
  FILE *fptr = NULL;
  char buffer[100];
  int idx = 0;

  fptr = fopen(CALIBRATION_FILENAME, "r");

  if (fptr != NULL)
  {
    while ((fgets(buffer, sizeof(buffer), fptr) != NULL) &&
           (idx < MAX_NUM_VALUES))
    {
      a_data[idx] = atoi(buffer);
      idx++;
    }

    fclose(fptr);
    fptr = NULL;
  }

  fptr = fopen(OLD_ROBOT_FILENAME, "r");

  if (fptr != NULL)
  {
    /* file exists, this is the 2009 robot */
    a_oldRobot = true;
    fclose(fptr);
    fptr = NULL;
  }

  fptr = fopen(PROTO_FILENAME, "r");

  if (fptr != NULL)
  {
    /* file exists, this is not the competition robot */
    a_competitionRobot = false;
    fclose(fptr);
    fptr = NULL;
  }

  printf("CALIBRATED FOR %s\n", a_competitionRobot ? "COMPETITION" : "PROTO");
}

/**
* Print the contents of the internal calibration data
*/
void WsCalibration::printValues()
{
  int idx;

  for (idx = 0; idx < MAX_NUM_VALUES; idx++)
  {
    printf("a_data[%d] %d\n", idx, a_data[idx]);
  }
}

/**
* Get function for the competition robot state
* @returns A boolean representing if the robot is the competition robot or not
*/
bool WsCalibration::isCompetitionRobot(void )
{
  return a_competitionRobot;
}

/**
* Get function for the old robot state
* @returns A boolean representing if the robot is the 2010 or 2009 robot
*/
bool WsCalibration::isOldRobot(void )
{
  return a_oldRobot;
}

/**
* Get the value of the desired calibration parameter
* @param index The index of the calibration parameter to get
* @returns The value of the calibration parameter
*/
UINT32 WsCalibration::getValue(CalibrationIndexT index)
{
    return a_data[index];
}

/**
* Get the value of the desired calibration parameter
* @param index The index of the calibration parameter to get
* @param value The value to write to the calibration parameter
*/
void WsCalibration::setValue(CalibrationIndexT index, UINT32 value)
{
  a_data[index] = value;
}

