//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsControllerMultiFunctionButton.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERMULTIFUNCTIONBUTTON_H)
#define _WSCONTROLLERMULTIFUNCTIONBUTTON_H

#include <stdio.h>
#include "WsControllerButton.h"


class WsControllerMultiFunctionButton : public WsControllerButton
{
    public:
        WsControllerMultiFunctionButton( Gamepad *p_pad,
                                         Gamepad::ButtonType actionButton,
                                         Gamepad::ButtonType shiftButton,
                                         bool usesShiftButton);

        virtual bool GetState(void );
    protected:
        Gamepad::ButtonType a_shiftButton;
        bool a_usesShiftButton;
        bool a_actionMode;
        bool a_shiftMode;
};

#endif  //_WSCONTROLLERMULTIFUNCTIONBUTTON_H
