//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControlMethod6WD.h
//  @ Date : 1/24/2011
//  @ Author : 
//
//


#if !defined(_WSCONTROLMETHOD6WD_H)
#define _WSCONTROLMETHOD6WD_H

#include <stdio.h>
#include "WsDriveVector.h"
#include "WsControllerPolarStick.h"
#include "WsDriveBase6WD.h"

class InputManager;
class WsDashboard;

#define SHIFTER_INPUT_HIGH false
#define SHIFTER_INPUT_LOW (!SHIFTER_INPUT_HIGH)
#define SPEED_DEADBAND (.05)

class WsControlMethod6WD
{
public:
    typedef enum
    {
        SHIFT_CMD_NONE,
        SHIFT_CMD_LOW,
        SHIFT_CMD_HIGH
    } ShifterCmdT;

    WsControlMethod6WD(void );
    ~WsControlMethod6WD(void );

    float getThrottle();
    float getTurnRate();
    void getDriveVector(WsDriveVector *driveVector);
    WsControlMethod6WD::ShifterCmdT getGearShifterState(void );
    bool getTurboState(void );
    void reset();


    float dashGetThrottle();
    float dashGetTurn();
    bool dashGetTurbo();
    bool dashGetShifter();


protected:
    WsControllerPolarStick *ap_polarStick;
    InputManager *ap_inputMgr;
    WsDashboard *ap_dashboard;
    WsDriveVector *ap_curDriveVector;
    float a_cachedThrottle;
    float a_cachedTurn;

    float a_turboScale;
};

#endif  //_WSCONTROLMETHOD6WD_H
