//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsControllerStickyButton.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSCONTROLLERSTICKYBUTTON_H)
#define _WSCONTROLLERSTICKYBUTTON_H

#include <stdio.h>
#include "WsControllerButton.h"

class Joystick;
class Gamepad;

/**
* This is a virtual button that retains its state until the button is pressed again.
* For example, the state starts at false and the button is not pressed.
* When the button is pressed, the state transitions to true.
* When the button is released, the state stays at true.
* When the button is pressed again, the state transitions to false.
*/
class WsControllerStickyButton : public WsControllerButton
{
public:
    WsControllerStickyButton(Joystick* p_js, UINT32 button);
    WsControllerStickyButton(Gamepad* p_pad, UINT32 button);
    WsControllerStickyButton(Gamepad* p_pad, Gamepad::ButtonType button);
    virtual ~WsControllerStickyButton();
    virtual bool GetState(void );
    virtual void ResetState(void);
protected:
    bool a_statePrev;   /*!< The previous state of the physical button */
    bool a_stickyState; /*!< The state of the virtual button */
};

#endif  //_WSCONTROLLERSTICKYBUTTON_H
