//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsControlMethodLarm.h
//  @ Date : 2/2/2011
//  @ Author : 
//
//


#if !defined(_WSCONTROLMETHODLARM_H)
#define _WSCONTROLMETHODLARM_H

#include <stdio.h>
#include "WsRollerClaw.h"
#include "WsLarm.h"
class InputManager;

class WsControlMethodLarm
{
public:
    static const float MANUAL_ARM_SCALE_FACTOR = .5;
    typedef enum
    {
        LARM_MODE_MANUAL,
        LARM_MODE_AUTO
    } LarmModeT;
    
    WsControlMethodLarm();
    ~WsControlMethodLarm();
    WsRollerClaw::RollerSpeedT getRollerClawCmd(void );
    WsRollerClaw::ReleaseStateT getClawReleaseState(void );
    float getArmSpeed(void );
    float getLiftSpeed(void );
    void readAutoLarmInputs(void );
    WsLarm::PositionT getLarmPosition(void );
    LarmModeT getLarmMode(void );
    void reset(void);

private:
    InputManager *ap_inputManager;

    WsLarm::PositionT a_larmPosition;
    LarmModeT a_larmMode;
    bool a_latchOutSlow;



};

#endif  //_WSCONTROLMETHODLARM_H
