//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsEncoderPot.h
//  @ Date : 1/22/2011
//  @ Author : 
//
//


#if !defined(_WSENCODERPOT_H)
#define _WSENCODERPOT_H
#include "WPILib.h"

#define SW_TOP_PRESSED  0
#define SW_BOT_PRESSED  0

class WsEncoder;

class WsEncoderPot {
public:
    WsEncoderPot(UINT32 encoder_a, UINT32 encoder_b, UINT32 bottom_sw, UINT32 top_sw);
    ~WsEncoderPot();
    INT32 getValue();
    bool isInitialized();
    bool isAtTop();
    bool isAtBottom();
protected:
    WsEncoder* ap_encoder;
    DigitalInput* ap_bot_sw;
    DigitalInput* ap_top_sw;
    bool a_initialized;
};

#endif  //_WSENCODERPOT_H
