//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsShmCamera.h
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#if !defined(_WSSHMCAMERA_H)
#define _WSSHMCAMERA_H

class WsShmCamera
{
public:
    WsShmCamera();
    ~WsShmCamera();
};

#endif  //_WSSHMCAMERA_H
