//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang
//  @ File Name : WsShmCamera.cpp
//  @ Date : 1/18/2010
//  @ Author : 
//
//


#include "WsShmCamera.h"
#include "WsVisionTask.h"
using namespace std;

WsShmCamera::WsShmCamera()
{
}

WsShmCamera::~WsShmCamera()
{

}



