//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2009
//  @ File Name : WsDriveVector.h
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#if !defined(_WSDRIVEVECTOR_H)
#define _WSDRIVEVECTOR_H

#include <stdio.h>

class WsDriveVector
{
public:
    float a_speed;
    float a_direction;
    float a_x;
    float a_y;
    WsDriveVector();
    WsDriveVector(float speed, float direction);
    WsDriveVector(float speed, float direction, float x, float y);
    void Reset();
    virtual ~WsDriveVector();
};

#endif  //_WSDRIVEVECTOR_H
