//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Wildstang 2010
//  @ File Name : WsDriveVector.cpp
//  @ Date : 1/14/2009
//  @ Author : 
//
//


#include "WsDriveVector.h"

WsDriveVector::WsDriveVector()
{
    Reset();
}

WsDriveVector::WsDriveVector(float speed, float direction)
{
    a_speed = speed;
    a_direction = direction;
    a_x = 0;
    a_y = -speed; // Y axis is inverted
}

WsDriveVector::WsDriveVector(float speed, float direction, float x, float y)
{
    a_speed = speed;
    a_direction = direction;
    a_x = x;
    a_y = y;
}

WsDriveVector::~WsDriveVector()
{
}

void WsDriveVector::Reset()
{
    a_speed = 0;
    a_direction = 0;
    a_x = 0;
    a_y = 0;
}
