//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsLineTrackerSensor.h
//  @ Date : 12/14/2010
//  @ Author : 
//
//


#if !defined(_WSLINETRACKERSENSOR_H)
#define _WSLINETRACKERSENSOR_H

#include <stdio.h>
class AnalogChannel;

class WsLineTrackerSensor
{
public:
    WsLineTrackerSensor(UINT32 slot, UINT32 channel);
    WsLineTrackerSensor(UINT32 slot);
    ~WsLineTrackerSensor();
    void SetThresholds(INT32 threshold);
    void SetThresholds(INT32 lightThreshold, INT32 darkThreshold);
    bool SeesLight(void );
    bool SeesDark(void );
    INT32 Get(void );
protected:
    AnalogChannel* a_analogChannel;
    INT32 a_lightThreshold;
    INT32 a_darkThreshold;
};

#endif  //_WSLINETRACKERSENSOR_H
