//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsLimitSwitch.h
//  @ Date : 12/14/2010
//  @ Author : 
//
//


#if !defined(_WSLIMITSWITCH_H)
#define _WSLIMITSWITCH_H

#include <stdio.h>
#include "DigitalInput.h"

class WsLimitSwitch
{
public:
    WsLimitSwitch(UINT32 channel, bool invert = false);
    WsLimitSwitch(UINT32 slot, UINT32 channel, bool invert = false);
    ~WsLimitSwitch();
    bool Get(void );
protected:
    DigitalInput* a_digitalInput;
    bool a_invert;
};

#endif  //_WSLIMITSWITCH_H
