//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsLightSensor.h
//  @ Date : 12/14/2010
//  @ Author : 
//
//


#if !defined(_WSLIGHTSENSOR_H)
#define _WSLIGHTSENSOR_H

#include <stdio.h>

class AnalogChannel;

class WsLightSensor
{
public:
    WsLightSensor(UINT32 slot, UINT32 channel);
    WsLightSensor(UINT32 channel);
    ~WsLightSensor();
    void SetThresholds(INT32 threshold);
    void SetThresholds(INT32 lightThreshold, INT32 darkThreshold);
    bool SeesLight(void );
    bool SeesDark(void );
    INT32 Get(void );
protected:
    AnalogChannel* a_analogChannel;
    INT32 a_lightThreshold;
    INT32 a_darkThreshold;
};

#endif  //_WSLIGHTSENSOR_H
