//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : WsUltrasonic.h
//  @ Date : 12/14/2010
//  @ Author : 
//
//


#if !defined(_WSULTRASONIC_H)
#define _WSULTRASONIC_H

#include <stdio.h>
#include "Ultrasonic.h"

class WsUltrasonic : public Ultrasonic
{
public:
    WsUltrasonic(DigitalOutput* pingChannel, DigitalInput* echoChannel, DistanceUnit units = kInches);
    WsUltrasonic(DigitalOutput& pingChannel, DigitalInput& echoChannel, DistanceUnit units = kInches);
    WsUltrasonic(UINT32 pingChannel, UINT32 echoChannel, DistanceUnit units = kInches);
    WsUltrasonic(UINT32 pingSlot, UINT32 pingChannel, UINT32 echoSlot, UINT32 echoChannel, DistanceUnit units = kInches);

    double Get(void);

    bool IsNumberInRange(double number, double distance);
    bool IsNumberInRange(double number, double min, double max);
    bool IsInRange(double distance);
    bool IsInRange(double min, double max);
};

#endif  //_WSULTRASONIC_H
